name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: first-apt-update
      run: sudo apt --allow-unauthenticated update
    - name: install-add-apt-repo
      run: sudo apt --allow-unauthenticated install software-properties-common
    - name: add-llvm-apt-sources
      run: sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" # &&  sudo add-apt-repository "deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
    - name: second-apt-update
      run: sudo apt --allow-unauthenticated update
    - name: install-build-tools
      run: sudo apt install ninja-build clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python-clang
    - name: configure-toolchain
      run: export CC=clang CXX=clang++
    - name: configure-build-directory
      run: mkdir build && cd build
    - name: cmake
      run:  cmake .. -DSTX_BUILD_TESTS=ON -GNinja
    - name: run-tests
      run: ninja run_tests
