name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: first-apt-update
      run: sudo apt --allow-unauthenticated update
    - name: install-add-apt-repo
      run: sudo apt --allow-unauthenticated install software-properties-common
    - name: add-llvm-apt-sources
      run: sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" # &&  sudo add-apt-repository "deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
    - name: second-apt-update
      run: sudo apt --allow-unauthenticated update
    - name: log
      run: sudo apt list clang*
    - name: install-build-tools
      run: sudo apt install ninja-build clang-format-10 clang-tidy-10 clang-tools-10 clang-10 clangd-10 libc++-10-dev libc++1-10 libc++abi-10-dev libc++abi1-10 libclang-10-dev libclang1-10 liblldb-10-dev lld-10 lldb-10 llvm-10-dev llvm-runtime llvm-10
    - name: configure-toolchain
      run: export CC=clang CXX=clang++
    - name: configure-build-directory
      run: mkdir build && cd build
    - name: cmake
      run:  cmake .. -DSTX_BUILD_TESTS=ON -GNinja
    - name: run-tests
      run: ninja run_tests
