name: cpp-17:gcc-12:ubuntu-22.04

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        build_mode: ["Release", "Debug"]

    steps:
      - uses: actions/checkout@v2

      - name: Install GCC, Absl, GTest, and Ninja
        run: sudo apt install gcc-12 g++-12 libabsl-dev libgtest-dev ninja

      - name: Configure Build Directory
        run: mkdir build

      - name: Build Tests
        run: cd build && cmake .. -DCMAKE_BUILD_TYPE=${{matrix.build_mode}} -DSTX_BUILD_TESTS=ON -DCMAKE_C_COMPILER=gcc-12  -DCMAKE_CXX_COMPILER=g++-12 -GNinja && ninja

      - name: Run Tests
        run: ./build/stx_tests
