name: cpp-17:gcc-12:ubuntu-22.04-qemu-arm

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        build_mode: ["Release", "Debug"]

    steps:
      - uses: actions/checkout@v3

      - name: Install Qemu, GCC ARM, and Ninja
        run: sudo apt update && sudo apt install qemu-user g++-arm-linux-gnueabi gcc-arm-linux-gnueabi ninja-build libc++abi1-15 libc++-15-dev libc++abi-15-dev lld-15 lldb-15 clang-15

      - name: Install GTest
        run: git clone https://github.com/google/googletest.git -b v1.13.0 --depth=1 third_party/googletest && cd third_party/googletest && mkdir build && cd build && cmake .. -DCMAKE_CXX_COMPILER=arm-linux-gnueabi-g++ -DCMAKE_C_COMPILER=arm-linux-gnueabi-gcc -GNinja && sudo ninja install

      - name: Build Tests
        run: mkdir build && cd build && cmake .. -DCLANG_TARGET_TRIPLE=armv7a-linux-eabi -DCMAKE_BUILD_TYPE=${{matrix.build_mode}} -DSTX_BUILD_TESTS=ON -GNinja -DCMAKE_CXX_FLAGS=-latomic -DCMAKE_EXPORT_COMPILE_COMMANDS=ON && cat compile_commands.json && ninja
        env: 
         CC: clang-15
         CXX: clang++-15

      - name: Run Tests
        run: qemu-arm -L /usr/arm-linux-gnueabi/ ./build/stx_tests
