name: cpp-17:clang-14:ubuntu-22.04

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        build_mode: ["Release", "Debug"]
        sanitize_flag:
          [
            "",
            "-fsanitize=address",
            "-fsanitize=undefined",
            #"-fsanitize=memory",
            #"-fsanitize=thread",
          ]

    steps:
      - uses: actions/checkout@v2

      - name: Configure Build Directory
        run: mkdir build

      - name: Install Absl, GTest, and Ninja
        run: sudo apt install libabsl-dev libgtest-dev ninja

      - name: Initialize CMake
        run: cd build && export CXXFLAGS="${{matrix.sanitize_flag}}"  && cmake .. -DCMAKE_BUILD_TYPE=${{matrix.build_mode}} -DSTX_BUILD_TESTS=ON -DCMAKE_C_COMPILER=clang-14 -DCMAKE_CXX_COMPILER=clang++-14 -GNinja && ninja

      - name: Run Tests
        run: ./build/stx_tests
