name: cpp-17:msvc-2019:windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        build_mode: ["Release", "Debug"]

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install VCPKG
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
        
      - name: Install Dependencies with VCPKG
        run: |
          cd vcpkg
          .\vcpkg.exe install --triplet x64-windows abseil gtest
          

      - name: Initialize CMake
        run: cmake -B ${{github.workspace}}/build -DSTX_BUILD_TESTS=ON -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build with CMake
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_mode}}

      - name: Run Tests
        run: ./build/${{matrix.build_mode}}/stx_tests.exe

