name: cpp-17:clang-14:macos-12

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-12

    strategy:
      matrix:
        build_mode: ["Release", "Debug"]

    steps:
      - uses: actions/checkout@v2

      - name: Install LLVM 14
        run: brew install llvm@14

      - name: Install GoogleTest
        run: brew install googletest

      - name: Install Abseil
        run: brew install abseil

      - name: Configure Build Directory
        run: mkdir build

      - name: Initialize CMake
        run: cd build && export CC=clang CXX=clang++ && cmake .. -DCMAKE_BUILD_TYPE=${{matrix.build_mode}} -DSTX_BUILD_TESTS=ON

      - name: Build Tests
        run: cd build && make

      - name: Run Tests
        run: ./build/stx_tests
