name: cpp-17:msvc-2019:windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2019

    strategy:
      matrix:
        build_mode: ["Release", "Debug"]

    steps:
      - uses: actions/checkout@v2

      - name: Fetch Absl
        run: git clone https://github.com/abseil/abseil-cpp.git -b 20220623.1 && cd abseil-cpp && mkdir build && cd build && cmake .. && cmake --build . --target install

      - name: Configure Build Directory
        run: mkdir build

      - name: Initialize CMake
        run: cd build && cmake .. -DSTX_BUILD_TESTS=OFF -Dgtest_force_shared_crt=ON

      - name: CMake Build
        run: cmake --build build --config ${{matrix.build_mode}}

      - name: Run Tests
        run: build/${{matrix.build_mode}}/stx_tests
