name: cpp-17:msvc-2019:windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        build_mode: ["Release", "Debug"]

    steps:
      - uses: actions/checkout@v3

      - name: Install VCPKG 
        run: git clone https://github.com/microsoft/vcpkg.git && cd vcpkg && ./bootstrap-vcpkg.bat
        
      - name: Configure Build Directory
        run: |
          rm -rf build
          mkdir build

      - name: Install STX Dependencies & Initialize CMake
        run: cd build && ls ../vcpkg/scripts/buildsystems && ../vcpkg/vcpkg.exe install --triplet x64-windows abseil gtest && cmake .. -DSTX_BUILD_TESTS=ON -DCMAKE_TOOLCHAIN_FILE="../vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: CMake Build
        run: cmake --build . --config ${{matrix.build_mode}}

      - name: Run Tests
        run: ./build/${{matrix.build_mode}}/stx_tests.exe
