name: cpp-17:gcc-12:ubuntu-22.04

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        build_mode: ["Release", "Debug"]

    steps:
      - uses: actions/checkout@v2

      - name: Install GCC
        run: sudo apt install gcc-12 g++-12

      - name: Install Absl
        run: sudo apt install libabsl-dev

      - name: Install GoogleTest
        run: sudo apt install libgtest-dev

      - name: Configure Build Directory
        run: mkdir build

      - name: Initialize CMake
        run: cd build && export CC=gcc-12 CXX=g++-12 && cmake .. -DCMAKE_BUILD_TYPE=${{matrix.build_mode}} -DSTX_BUILD_TESTS=ON

      - name: Build Tests
        run: cd build && make

      - name: Run Tests
        run: ./build/stx_tests
