name: cpp17:msvc2019:windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2019

    strategy:
      matrix:
        build_mode: ["Release", "Debug"]

    steps:
      - uses: actions/checkout@v2

#- name: Install GoogleTest
#run: git clone https://github.com/google/googletest.git && cd googletest && mkdir build && cmake --build . --config ${{ matrix.build_mode }} && cmake --install . && cd .. && cd ..

      - name: Configure Build Directory
        run: mkdir build

      - name: Initialize CMake
        run: cd build && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_mode }} -DSTX_BUILD_TESTS=ON -Dgtest_force_shared_crt=ON

      - name: CMake Build
        run: cmake --build build

      - name: Run Unsanitized Tests
        run: cd build && Debug\stx_tests.exe
