name: tests:windows


on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }} 

    strategy:

      matrix:
        os: ["windows-2019"]
        build_mode: ["Release", "Debug"]
        panic_backtrace: ["ON", "OFF"]
        backtrace: ["ON", "OFF"]

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure Build Directory
        run: mkdir build

      - name: Initialize CMake
        run: cd build && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_mode }} -DSTX_BUILD_TESTS=ON -DSTX_ENABLE_BACKTRACE=${{ matrix.backtrace }} -DSTX_ENABLE_PANIC_BACKTRACE=${{ matrix.panic_backtrace }} -DSTX_SANITIZE_TESTS=OFF

      - name: Run Unsanitized Tests
        run: cd build && make stx_tests &&  .\stx_tests

